[package]
name = "dao_generator"
version = "1.0.0"
authors = []

[addresses]
dao_generator_addr = '0xa0980e2efd99261b8769d684b5eaf36aa31fef5b6bdbe65f0eac087168abf71d'
token_addr         = '0xa0980e2efd99261b8769d684b5eaf36aa31fef5b6bdbe65f0eac087168abf71d'
fee_receiver_addr  = '0xa0980e2efd99261b8769d684b5eaf36aa31fef5b6bdbe65f0eac087168abf71d'

# [dev-addresses]
# dao_generator_addr = '0x111'
# fee_receiver_addr  = '0x222'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]