[package]
name = "basedao"
version = "1.0.0"
authors = []

[addresses]
basedao_addr = '_'
token_addr         = '_'
fee_receiver_addr  = '_'

# basedao_addr       = '0x80fc7c711b3eeef9dc4d46cf2682196478a7dc5c6efaa49af7a5bffdb91c657a'
# token_addr         = '0x80fc7c711b3eeef9dc4d46cf2682196478a7dc5c6efaa49af7a5bffdb91c657a'
# fee_receiver_addr  = '0x80fc7c711b3eeef9dc4d46cf2682196478a7dc5c6efaa49af7a5bffdb91c657a'

[dev-addresses]
basedao_addr       = '0x111'
fee_receiver_addr  = '0x222'
token_addr         = '0x333'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]